Added test on search functionality
tr0yyy/proiect-tss pull request #6
Opened 2023-04-21 17:01 UTC by CristianUlmeanu

2023-04-21 17:07 UTC, tr0yyy requested changes

2023-04-21 17:07 UTC, tr0yyy commented on src/main/java/autotest/tests/ArticolTest.java
> +        getDriver().findElement(homeUi.searchHome).sendKeys(titlu);
move this in another test method

2023-04-21 17:59 UTC, CristianUlmeanu commented on src/main/java/autotest/tests/ArticolTest.java
> +        getDriver().findElement(homeUi.searchHome).sendKeys(titlu);
Changes implemented.

2023-04-21 20:41 UTC, CristianUlmeanu commented
I also created the test for the sorting feature, please check that as well.
Ty :)

2023-04-22 18:28 UTC, tr0yyy requested changes

2023-04-22 18:28 UTC, tr0yyy commented on src/main/java/autotest/tests/ArticolTest.java
> +        creazaArticol(titlu, domeniu, continut);
this functions does not have search logic
a search function should not create a new article everytime

2023-04-22 18:28 UTC, tr0yyy commented on src/main/java/autotest/tests/ArticolTest.java
> +        searchArticol(titlu, domeniu, continut);
call createarticol above searcharticol

2023-04-30 14:19 UTC, tr0yyy commented
Rejected due unnecessary tests.

2023-04-30 14:19 UTC, closed without merging